package io.github.cottonmc.functionapi.api.content.enums;

public enum BlockSoundGroup {
    BAMBOO, BAMBOO_SAPLING, CORAL, CROP, GLASS, GRASS, GRAVEL, LADDER, LANTERN, METAL, NETHER_WART, SAND, SCAFFOLDING, SLIME, SNOW, STEM, STONE, SWEET_BERRY_BUSH, WET_GRASS, WOOD, WOOL, ANVIL
}
